### ISSUE TITLE
create a content selector plugin

### ISSUE THREAD

**Issue by hbaptiste** [backbee/BbCoreJs#106]
This plugin will allow us to add new contents to a contentset. The ContentSelector should only allow the selection of contents that the contentset accepts.

**Comment by mickaelandrieu** [comment]
:+1: it's time to make things just "works" !

**Comment by fkroockmann** [comment]
@hbaptiste, its done ?

**Comment by hbaptiste** [comment]
it has been done ... and tested :)

**Comment by fkroockmann** [comment]
Thanks, good job :)
