### ISSUE TITLE
Selected tab should more visible

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#113]
Clicking on the header tabs, the selected state is not clearly visible (grey on black) ...choose another color for selected state.

**Comment by mickaelandrieu** [comment]
@clementbonfils what colour should be used ? Did you have any example on others tools ?

**Comment by clementbonfils** [comment]
this colour 
#e34c26
it is already a used variable

**Comment by clementbonfils** [comment]
voir avec Julien en intégration
