### ISSUE TITLE
Better add a popin to confirm the activation/desactivation of a bundle  

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#114]
Better add a popin to confirm the activation/desactivation of a bundle  

Activating desactivating a bundle can be a key issue, in case of missclick it is important to have this security.

**Comment by fkroockmann** [comment]
Waiting merge PR 228 of bbcorejs
Waiting fix to retrieve config of bundle @eric-chau

**Comment by clementbonfils** [comment]
ok
