### ISSUE TITLE
[Contribution] [Content] [Plugin] + add plugin '+' on contentset

### ISSUE THREAD

**Issue by fkroockmann** [backbee/BbCoreJs#126]
This plugin add content directly in the contentset.
When contentset don't have accept, i will show a popin for choose a content.

**Comment by fkroockmann** [comment]
Have you got an idea for the name of this plugin ? ping @backbee/core-team

**Comment by mickaelandrieu** [comment]
ContentSetPopupatorManagerPlugin

**Comment by fkroockmann** [comment]
:+1:

**Comment by ndufreche** [comment]
AddContentPlugin

**Comment by fkroockmann** [comment]
@mickaelandrieu can you create a vote ? ^^

**Comment by mickaelandrieu** [comment]
This is not possible in github.

Are we agree that the plugin name should be enough explicit to understand what it does ?
