### ISSUE TITLE
Edit a user

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#181]
- the pop in goes benhind the content (html issue ?)
- missign field must be warned by a much more visible warning (red)
- if password is generated automatically and sent to user, it must be told and the password field should not be visible at first registration
- if there are restrictions in terms of numbers of type of caracteres it must be told
- can't re-edit a user after making a fform filling error
- if validation of the form fail, the source of the error must be told
- i can register with a similar mail as another user , i shoud not
- i can register with a similar name and surname as another user , i should not

**Comment by ndufreche** [comment]
> the password field should not be visible at first registration

* The password is not visible.


> if there are restrictions in terms of numbers of type of caracteres it must be told

* Actually is told on validation with the error message.


> i can register with a similar name and surname as another user , i should not

* There is no surname 
* User can't have similar name? that can be problematic.


> can't re-edit a user after making a fform filling error

and 

> if validation of the form fail, the source of the error must be told

* This is happen in only one case (if your the e-mail that you submit pass the JS test and not the PHP test) but this have to be fix.

**Comment by clementbonfils** [comment]
still can add news users with same email adress...I should not

**Comment by clementbonfils** [comment]
still can add a new user with same name surname I should not

**Comment by clementbonfils** [comment]
delete confirmation pop in has a different style fromthe other looks like bootstrap
Must be harmonized with the other delete pop in
