### ISSUE TITLE
Tree - right click

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#183]
- right clicking on a page in the tree pop in should display a pop in 
![tree right click](https://cloud.githubusercontent.com/assets/10673014/6230146/a904c37a-b6bd-11e4-85e1-ef0906a808f7.png)

- edit doesn't work ..keep loading
- create doesn't work...keep loading

**Comment by fkroockmann** [comment]
Waiting merge PR 92 and 94 of backbee-standard.

**Comment by clementbonfils** [comment]
ok
