### ISSUE TITLE
Introduce a new core library: Translator

### ISSUE THREAD

**Issue by mickaelandrieu** [backbee/BbCoreJs#202]
Hi everyone,

I suggest to add into core a new component called Translator in charge of dealing with the locale selected for the toolbar.

in my opinion, this should stay as simple as possible. This is the implementation I suggest for now:

```js
define('tb.core.Translator', ['require', 'tb.core.Api'], function (require) {
    'use strict';

        /*
         * BackBee Translator core library
         * Allow to set multiples dictionnary files
         *
         * Can be accessed throught templates using global function 'trans'
         * Ex: <h1>{{ trans('hello_world') }}</h1> will return "Hello world"
         *
         * // global.en_US.js
         * {
         *      'hello_world' : 'Hello world'
         * }
         */
    var Translator = {
            getLocale:  function (config) {
                // get locale from config, can be overidden
            },

            setLocale: function (locale) {
                // check for availables files, throw exception else and set a default locale
            },
        
            getDefaultLocale: function () {
                return 'en_US';
            }

            trans: function (key, dictonnary) {
                if (dictionnary === undefined) {
                    dictionnary = 'global';
                }
                // get dictionnary
                // return value or throw exception
            },

            getDictionnary: function (name) {
                // how to access translation files ? 
            }
        };

    return Translator;
});
```

With, at least a dictionnary file we can store in ``/src/tb/translations`` new folder:
```js
// global.en_US.fr
{
    'app.validate' : 'Validate'
}
```

Also, I need to make a new helper ``trans`` available in templates to be able to use the translator in templates:

```twig
// apps/bundle/templates/index.twig
<button type="submit" value="{{ trans('app.validate') }}" />
```

I'm not very easy with BbCoreJS or with javascript, I need a little help to access dictionnary files or make my helper available in templates in the *right way*.

ping @ndufreche @hbaptiste  @fkroockmann

**Comment by hbaptiste** [comment]
You gonna need a config that will tell us where to find the translation files
and maybe a require plugin to load those files

**Comment by fkroockmann** [comment]
You can see a doc of nunjucks for create a helper or you can inject a function 'trans' into a Renderer for be usable anywhere.

Good idea :)

**Comment by ndufreche** [comment]
Good idea.
Then I don't like the principle of use key, I prefer do a translation directly English to other language.
The advantage is if the translation is not already available the word still comprehensive.

**Comment by ndufreche** [comment]
@hbaptiste yes the require plugin, is the best option.

**Comment by mickaelandrieu** [comment]
@hbaptiste did you mean we have to add a new key to config.js file ? 
@fkroockmann did you have any link ? or any implementation already done in BbCoreJs I can declined for my need ?

@ndufreche you are right but as we will provide for sure a complete traduction file for en_US we are ok with this, if a key is not found in the selected locale, the translator will use the default locale which is the only we will assure to maintain over years.

Are you ok with this, so ?

**Comment by ndufreche** [comment]
@backbee/core-team i18n library https://github.com/mozilla/i18n-abide

**Comment by ndufreche** [comment]
Ok, I'm fine for the keyword, but we have to normalize the key and for that we can use [Uniform Resource Identifier (URI): Generic Syntax](https://tools.ietf.org/html/rfc3986)
And for help we can use this node library https://github.com/dodo/node-slug

And there is implementation command (file named "slug") :

```javascript
#!/usr/bin/env node

var slug = require('slug');
var print = console.log.bind(console, '>');

print(slug(process.argv[2]));
```

And can be used like this
```bash
./slug 'validate something before save'
```

**Comment by fkroockmann** [comment]
@mickaelandrieu, this issue is done ?
