### ISSUE TITLE
Export DND from content to an plugin

### ISSUE THREAD

**Issue by fkroockmann** [backbee/BbCoreJs#210]
Currently, we can dnd a block directly.

**Comment by ndufreche** [comment]
Ok I have fix the dnd in chrome.
To set the dnd functional in FireFox, we need to transform the buttons into div

**Comment by ndufreche** [comment]
there is an update of toolbar-bundle to ndufreche/ToolbarBundle:210

**Comment by clementbonfils** [comment]
still cant' dnd block (using chrome)

**Comment by clementbonfils** [comment]
ok fixed

**Comment by clementbonfils** [comment]
no drop zone visible on FF no DND possible
