### ISSUE TITLE
"+" button

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#253]
- if there is no choice between different block, add the block directly
- if there is a choice between different blocks show a drop down
- adding the image block with the "+", it adds 5 images

**Comment by fkroockmann** [comment]
This is already done no ? @clementbonfils

**Comment by clementbonfils** [comment]
yes but When i add an image block 5 of them are added

**Comment by clementbonfils** [comment]
still two images are added when i choose to add an image block
