### ISSUE TITLE
Translation of BbCoreJS

### ISSUE THREAD

**Issue by mickaelandrieu** [backbee/BbCoreJs#266]
There are the folder to be checked before the *1.0* release.

I will address many pull requests.

- [ ] Components
    - [ ] authentication
    - [ ] cke
    - [ ] content selector
    - [ ] context menu
    - [ ] data store
    - [ ] data view
    - [x] dnd
    - [x] exceptions-viewer
    - [ ] form builder
    - [ ] link selector
    - [x] logger
    - [ ] mask
    - [x] notify
    - [ ] pagination
    - [ ] popin
    - [ ] range selector
    - [ ] revision selector
    - [ ] rte manager
    - [x] translator
    - [ ] tree view
- [ ] apps
    - [x] bundle
    - [ ] content
    - [x] contribution
    - [x] layout (not needed)
    - [x] main
    - [x] page
    - [ ] user

**Comment by ndufreche** [comment]
User is actually ok.
dnd, exceptions-viewer, logger, notify, translator there is no translation to do

**Comment by mickaelandrieu** [comment]
hmm, imo we "can't" translate Authentication because we don't have access to the configuration at this point: https://github.com/backbee/BbCoreJs/blob/master/src/tb/init.js#L74

Can someone confirm ?

**Comment by ndufreche** [comment]
I think but the authentication, is not goodly implemented. We have to rethink it.

**Comment by mickaelandrieu** [comment]
@ndufreche I suggest to start by a simple "template" translation here, and take time to think about strategy for forms/popins and authentication /c @fkroockmann /c @hbaptiste

**Comment by mickaelandrieu** [comment]
@ndufreche what is the actual state of this ? Does it miss translations ?
