### ISSUE TITLE
create specs for core Renderer

### ISSUE THREAD

**Issue by mickaelandrieu** [backbee/BbCoreJs#27]

**Comment by fkroockmann** [comment]
@mickaelandrieu, it's done no ?

**Comment by ndufreche** [comment]
Renderer isn't fully tested I reopen it.

**Comment by mickaelandrieu** [comment]
it is, the only method non tested is ``asyncRender`` which actualy don't works as expected (and non used in BBcoreJs)

**Comment by ndufreche** [comment]
Nop, Render exception and initRenderer isn't tested :)

**Comment by mickaelandrieu** [comment]
Fair enough, I will add them tommorrow.

**Comment by ndufreche** [comment]
I close this ticket Renderer object is no more in this repo
