### ISSUE TITLE
[Extensions][master] The list show but, don't hide

### ISSUE THREAD

**Issue by mickaelandrieu** [backbee/BbCoreJs#272]
When you click on "see my extensions", the list of registered bundles appears => good behavior

But when you click again on the arrow on the left of "See my extensions", the list is not hidden.

![bug-extensions](https://cloud.githubusercontent.com/assets/1247388/6523026/06c5dc02-c3ec-11e4-9d29-f0948883d874.png)

**Comment by clementbonfils** [comment]
Ok bug fixed
