### ISSUE TITLE
Add composer.json file

### ISSUE THREAD

**Issue by mickaelandrieu** [backbee/BbCoreJs#306]
Hi,

I need BbCoreJs to be requested by composer. Can you add a composer.json file ?

Regards,

**Comment by ndufreche** [comment]
Yes, I will do that in same time of the distributed version.

**Comment by mickaelandrieu** [comment]
It's not mandatory, but this can help me, for now I add BbCoreJS this way => https://github.com/backbee/ToolbarBundle/blob/master/composer.json#L16

**Comment by mickaelandrieu** [comment]
we need this to bump the first 1.0.0 of backbee-standard /c @nicolas_bastien
