### ISSUE TITLE
rename bb5-ui.css to bb-ui.css

### ISSUE THREAD

**Issue by mickaelandrieu** [backbee/BbCoreJs#312]
In ToolbarBundle, we request ``bb-ui.css`` file => https://github.com/backbee/ToolbarBundle/blob/master/Resources/views/partials/bbtoolbar.twig#L2

So I guess we need to update BbCoreJs filename in ``html/css`` folder ?

ping @ndufreche

**Comment by ndufreche** [comment]
this is already done normally.

**Comment by mickaelandrieu** [comment]
Sadly, not available in master branch (https://github.com/backbee/BbCoreJs/blob/master/html/css/bb5ui.css)

**Comment by mickaelandrieu** [comment]
I think it's a "typo" ahaha

**Comment by ndufreche** [comment]
bb-ui is generated from the less sources. But if it stay a bb5ui.css file we have to delete it.
