### ISSUE TITLE
CKeditor

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#344]
- pop in from the editor should not be hidden by the interface
- "cut" doesn t work on chrome using the button
- how does the "ancre" works ?

**Comment by clementbonfils** [comment]
editor doesn't work
![ck](https://cloud.githubusercontent.com/assets/10673014/7249787/3bf3ada0-e81d-11e4-9ed1-6a03cbff9f85.png)

**Comment by mickaelandrieu** [comment]
confirmed.

**Comment by clementbonfils** [comment]
-  all pop in must be upon the interface @jtrolle 
- delete ancre 
- delete "a propos de CK editor"
![pop](https://cloud.githubusercontent.com/assets/10673014/7393069/04e2b82c-ee8c-11e4-948f-206b1883cf07.png)

**Comment by ndufreche** [comment]
Please @clementbonfils create a new issue for CKE integration and close this one if is ok.
