### ISSUE TITLE
Drag&drop of blocks don't work as expected with FF 35/ubuntu 14.04

### ISSUE THREAD

**Issue by mickaelandrieu** [backbee/BbCoreJs#360]
The drag & drop is not active and no allowed zones are displayed but we can add content through the edit icon option.

As a comment:

* if we select the media block in "block" view, we can then in "content" view drag an image into the container, this may be a "binding" issue.

**Comment by clementbonfils** [comment]
@jtrolle

**Comment by ndufreche** [comment]
@mickaelandrieu  in firefox the drag and drop of button tag is not allowed.

To fix this issue, we have to transform the button tag into div tag and re-skin this div into with the actually button style.

**Comment by mickaelandrieu** [comment]
@jtrolle @ndufreche ok, thank you for informations.

**Comment by clementbonfils** [comment]
button tags are switched on a tags
Need reskin
