### ISSUE TITLE
pages are not displayed in internal link

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#397]
cliking on the tree in link selector, i can"t see pages

**Comment by clementbonfils** [comment]
![link](https://cloud.githubusercontent.com/assets/10673014/7365002/880113a8-ed8c-11e4-8dff-c90aa0851665.png)

**Comment by ndufreche** [comment]
I think you have forgot to set the children page online. retry some page online, it works fine for me

**Comment by fkroockmann** [comment]
Try it on article page

**Comment by clementbonfils** [comment]
you are right the page has to be online to be visible
maybe we can show offline pages with a grey filter on it and non clickable
A message  "online pages only can be selected" woud be great to display !
We need a real button for page selection @jtrolle 
![select](https://cloud.githubusercontent.com/assets/10673014/7366214/e05b06b2-ed96-11e4-964b-2a0f8ab64d82.png)

**Comment by clementbonfils** [comment]
still no pages displayed 
was the modification merged ?

**Comment by clementbonfils** [comment]
ok it work
see with @jtrolle  to add button for "select"  and clean the pop in
