### ISSUE TITLE
can't delete a user from a group

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#401]
![user](https://cloud.githubusercontent.com/assets/10673014/7349093/ea5de8be-ecf6-11e4-8285-4788e79214bb.png)

**Comment by mickaelandrieu** [comment]
It's not part of specifications for 1.0 (as said to me @ndufreche ), so please move the milestone to 1.1.

Also, you can see an non translated key. (write_and_acess), I suggest ``write_and_access`` and "Write and access" as a translation.

**Comment by ndufreche** [comment]
Yeah the removing user from a group is not planned for now

**Comment by clementbonfils** [comment]
put a remove button
![Uploading ea5de8be-ecf6-11e4-8285-4788e79214bb.png…]()
