### ISSUE TITLE
can 't see all the blocks in the "pick a block section" SLIDE KO

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#427]
![block](https://cloud.githubusercontent.com/assets/10673014/7414889/d6b35144-ef55-11e4-8f77-ab928521dc1e.png)

**Comment by clementbonfils** [comment]
remove delete plug in if content parent is not a contentset

**Comment by jtrolle** [comment]
@mickaelandrieu do you load bootstrap javascript ? bootstrap.min.js is required for carousel

**Comment by mickaelandrieu** [comment]
@jtrolle I realy don't know. I was'nt involved in this feature. (see #474)

**Comment by ndufreche** [comment]
@jtrolle yes bootstrap is loaded. But I investigate more deeply

**Comment by eric-chau** [comment]
ping @clementbonfils, you can test it right now.
