### ISSUE TITLE
date picker in content selector

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#435]
- search by date doesn't work
- select month and year is not clean
![picker](https://cloud.githubusercontent.com/assets/10673014/7456360/3a6c76bc-f284-11e4-8a4c-e9a906989889.png)

**Comment by clementbonfils** [comment]
aspect is Ok but display is way too far from the search field
![pick](https://cloud.githubusercontent.com/assets/10673014/7684404/0250c8ca-fd86-11e4-857c-beda2eef7331.png)

**Comment by jtrolle** [comment]
the datetimepicker of publishing/archiving is generated at the end of the body but must be placed in .bb5-ui.
