### ISSUE TITLE
pages of the tree disapear

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#437]
When i change status of a new page (from offline to online) pages of my tree dispaear
I have to create a new page then refresh to have my pages back

**Comment by ndufreche** [comment]
When we are on this bug. The getCollectionAction from page rest controller in BackBee (core php) respond only the Home page and the java script become with the home opened without is children visible.
@fkroockmann and @eric-chau you can watch this point ?

**Comment by eric-chau** [comment]
Strange behavior yeah cause I checked the call to REST API and seems that it returns the right children of the home page but they are not displayed. I think we should asking for @fkroockmann to check the js side.
