### ISSUE TITLE
plug in are not accessible when they are on th every top block of the page

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#459]
![top](https://cloud.githubusercontent.com/assets/10673014/7494511/4f82b5cc-f408-11e4-925a-deeb546b1e63.png)

**Comment by mickaelandrieu** [comment]
https://github.com/backbee/backbee-standard/issues/144

**Comment by clementbonfils** [comment]
@jtrolle 
COntent set has now plugin, so the bug remains
![contenset](https://cloud.githubusercontent.com/assets/10673014/7613291/29394812-f990-11e4-8442-39ca18d170c4.PNG)
