### ISSUE TITLE
archiving date can't be before publishing date in page calendar

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#493]
- [x] disable past dates for publishing : i can't publish a page in the past
- [x] disable archiving date before today
- [ ] disable archiving date before the publishing date

**Comment by mickaelandrieu** [comment]
Hi, I'm on it.

**Comment by clementbonfils** [comment]
publishing and archiving date are  not saved after page reloading 
find a way to link publishing and archiving dates please

**Comment by mickaelandrieu** [comment]
1/ you need to save and validate
2/ I can't by design: theses date are saved at the same time.
