### ISSUE TITLE
orphaned media KO in library

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#541]
after adding an image to an article, the image is stil considered orpahned in the libarry when i want to delete it

**Comment by eric-chau** [comment]
This issue is resolved by [backbee/backbee PR #398](https://github.com/backbee/BackBee/pull/398).

Keep in mind that it returns linked pages only in case that you validate your drafts.

**Comment by eric-chau** [comment]
ping @clementbonfils, you can test it right now.

**Comment by clementbonfils** [comment]
thanks !
