### ISSUE TITLE
error message when logged in

### ISSUE THREAD

**Issue by geoffroyjourdan** [backbee/BbCoreJs#556]
I tried to logg in with a fake login and password, and the message which appears is "Bad credentials"

Should we replace this message by something like : login or password incorrect. Please, try again. @clementbonfils

**Comment by clementbonfils** [comment]
write : login or password incorrect

**Comment by mickaelandrieu** [comment]
Hi, I'm on it.

**Comment by mickaelandrieu** [comment]
https://github.com/backbee/BbCoreJs/pull/614
