### ISSUE TITLE
Home backoffice / CHROME

### ISSUE THREAD

**Issue by celine-user03** [backbee/BbCoreJs#558]
![picture01](https://cloud.githubusercontent.com/assets/12509154/7698488/fed0a806-fe10-11e4-9c7f-2b3a6cf31239.png)
After a login error , displaying the BO does not conform to the expected version.(see the attached picture). To view the menu , I have to refresh the page.

**Comment by clementbonfils** [comment]
thanks for this report a ticket is already open #502
