### ISSUE TITLE
navigation tabs / IE 10

### ISSUE THREAD

**Issue by celine-user03** [backbee/BbCoreJs#560]
sometimes when I switch from one tab to another an error window appears
![picture02 fw](https://cloud.githubusercontent.com/assets/12509154/7698797/5bbc2a0c-fe13-11e4-9ee0-cb4164518d4b.png)

**Comment by clementbonfils** [comment]
its a loading message
does the pop in stay like this or display user management afterall?

**Comment by celine-user03** [comment]
I have to refresh the page to see all items
