### ISSUE TITLE
Resize Pop in Tree

### ISSUE THREAD

**Issue by celine-user03** [backbee/BbCoreJs#561]
When we resize the popin in tree section, in the case of a long page name, the title of the page is hidden by the size of the window. The text should return to the line
![picture03 fw](https://cloud.githubusercontent.com/assets/12509154/7699159/284f471e-fe16-11e4-840b-bef56ce56e64.png)

**Comment by clementbonfils** [comment]
interesting enhancement
we will get on it for the 1.1 version
