### ISSUE TITLE
Menu contextuel Tree : "copy"

### ISSUE THREAD

**Issue by celine-user03** [backbee/BbCoreJs#565]
the little black arrow before the name of the page is missing after you use the copy / paste function
![picture04 fw](https://cloud.githubusercontent.com/assets/12509154/7700116/a42bf4b2-fe1c-11e4-98e0-a987b9856dd0.png)

**Comment by clementbonfils** [comment]
if page doesn't have children then, there is no arrow

**Comment by celine-user03** [comment]
ok.
But in this case thers is a bug (see photo below)
![picture05 fw](https://cloud.githubusercontent.com/assets/12509154/7703386/e384065c-fe37-11e4-9d0d-003ac262e844.png)
