### ISSUE TITLE
dont highlight and underline content and image names in their library 

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#588]
![underline](https://cloud.githubusercontent.com/assets/10673014/7703419/1eb708b4-fe38-11e4-8ac0-1bc87bb8b097.png)
dont highlight and underline content and image names in their library

**Comment by clementbonfils** [comment]
@jtrolle doesn't work on CHROME

**Comment by jtrolle** [comment]
replace `<a>` by `<strong class="txt-highligth">`

**Comment by fkroockmann** [comment]
@hbaptiste can you do that ?

**Comment by mickaelandrieu** [comment]
@jtrolle is it ``txt-highligth`` or ``txt-highlight`` ?
