### ISSUE TITLE
In Status pop in change hidden for "Not available in menu" and "Available in menu"

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#590]
![menu](https://cloud.githubusercontent.com/assets/10673014/7703575/268fe064-fe39-11e4-823e-c9959f4138bd.png)

**Comment by mickaelandrieu** [comment]
![yoyo](https://cloud.githubusercontent.com/assets/1247388/7774731/e132e5da-00ad-11e5-8558-b5601fd297b2.png)
![yoyo2](https://cloud.githubusercontent.com/assets/1247388/7774732/e289dfd8-00ad-11e5-9ee3-0789d93b860c.png)
![page_status](https://cloud.githubusercontent.com/assets/1247388/7774733/e3c74b9c-00ad-11e5-82d4-f1507e66f961.png)

**Comment by mickaelandrieu** [comment]
We don't have the information from API when the page is available on menus, and I don't think this is actualy required as the user SEE the menu.
