### ISSUE TITLE
don't display no selected effect on tree/contents/media library/new page after the end of action

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#598]
for exemple i enter the media library clicking on its button, when i close the library the button must not be selected
![red](https://cloud.githubusercontent.com/assets/10673014/7703936/722ca9d8-fe3b-11e4-950a-f4910b21ce3f.png)

**Comment by jtrolle** [comment]
Fixed with a previous PR, see issue #649
