### ISSUE TITLE
In cancel pop in put "confirm" and not "save" in the button

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#599]
In cancel pop in put "confirm" and not "save" in the button

**Comment by mickaelandrieu** [comment]
@clementbonfils which one ? can you provide a screen capture please  :)

**Comment by Sylvain01** [comment]
it is the "Cancel Confirmation" pop in
![cancel-popin](https://cloud.githubusercontent.com/assets/12500378/7710662/a2d348ba-fe65-11e4-8230-4d87accea85c.PNG)

**Comment by mickaelandrieu** [comment]
@Sylvain01 thanks, I'm on it.
