### ISSUE TITLE
cancel and validation pop in must be displayed on top of the page

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#605]
cancel and validation pop in must be displayed on top of the page for user to see it all

**Comment by mickaelandrieu** [comment]
on top but on top from how many pixels ? can you provide me a capture :)

**Comment by clementbonfils** [comment]
![pop](https://cloud.githubusercontent.com/assets/10673014/7727510/774d3b52-ff09-11e4-9f9b-9f30b08e1cda.png)

**Comment by mickaelandrieu** [comment]
thanks @clementbonfils, I'm on it.
