### ISSUE TITLE
The author's name should not be "A.Noname *" in pop in

### ISSUE THREAD

**Issue by Sylvain01** [backbee/BbCoreJs#608]
The author's name should not be "A.Noname *" in pop in
![no-name](https://cloud.githubusercontent.com/assets/12500378/7710194/8a07e622-fe62-11e4-809c-421afb3676dc.PNG)

**Comment by mickaelandrieu** [comment]
@ndufreche can I access to the logged user at this moment ? (like in the top tool bar ?)

**Comment by ndufreche** [comment]
Yes, but is not the problem. Your author name should be not A.Noname, but the user haven't name, this is just a place holder.

**Comment by mickaelandrieu** [comment]
Yep, I know A.Noname is "hardcoded", but i suggest to change this state by an {{ loggedUser.username }} atm.

But ... what is the interest of this column if we are author of all of "our" modifications ? this make no sense.
