### ISSUE TITLE
My name is not "undefined"

### ISSUE THREAD

**Issue by Sylvain01** [backbee/BbCoreJs#609]
My name is not "undefined"
![undefined](https://cloud.githubusercontent.com/assets/12500378/7710269/f7d7458a-fe62-11e4-9811-77c0092afaaa.PNG)

**Comment by clementbonfils** [comment]
This issue has been reported already
The signature is now editable in the artcile form as you can see on the screen shot

![signature](https://cloud.githubusercontent.com/assets/10673014/7721676/d2aae592-fed9-11e4-9e37-4c0768340e83.png)
