### ISSUE TITLE
When I use the scheduled on line edition, it creates invalid dates

### ISSUE THREAD

**Issue by Sylvain01** [backbee/BbCoreJs#611]
1) I use the scheduled on line edition > I select a date & an hour 
2) I go to another page
2) I come back to the "scheduled page" > the dates became "invalid"
![invalid-dates](https://cloud.githubusercontent.com/assets/12500378/7711271/bf597776-fe69-11e4-92a8-d1446c9b7dca.PNG)

**Comment by clementbonfils** [comment]
this issue has already been reported 
thanks for your attention
