### ISSUE TITLE
users of a group pop in

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#628]
Give a name to the pop in : "users of the group"
display a message when there are no users in the group : "no users in this group"
![pop user](https://cloud.githubusercontent.com/assets/10673014/7728965/7dc9dcca-ff12-11e4-9f74-01bcfb84f74b.png)

**Comment by clementbonfils** [comment]
Or disable user button if no user is present in the group

**Comment by clementbonfils** [comment]
@sylvain01 which option do you prefer ?

**Comment by Sylvain01** [comment]
We display a message when there are no users in the group : "No users in this group"

**Comment by clementbonfils** [comment]
ok

**Comment by ndufreche** [comment]
"users of the group" or "users in the group" or "group's user" ?

**Comment by Sylvain01** [comment]
Please ask Joseph
Thanks

**Comment by clementbonfils** [comment]
issue is not fixed yet
