### ISSUE TITLE
[USERS] HTML integration problem when reducing the size of the user window

### ISSUE THREAD

**Issue by Sylvain01** [backbee/BbCoreJs#640]
HTML integration problem when reducing the size of the user window
![user](https://cloud.githubusercontent.com/assets/12500378/7734610/7b90c372-ff37-11e4-8741-7f4fa3201f63.PNG)

**Comment by clementbonfils** [comment]
Did you get my email to have @jtrolle on those html issues ?

**Comment by jtrolle** [comment]
It is possible to add/increase a minimum width on the dialog. Add 'minWidth': 350

**Comment by clementbonfils** [comment]
make the pop in large and wide then disable pop in resize
