### ISSUE TITLE
Title section highlighted

### ISSUE THREAD

**Issue by geoffroyjourdan** [backbee/BbCoreJs#642]
When I click on the contribution section, the User management section is "highlighted" whereas I'm not into this one.

see file attached
![user management](https://cloud.githubusercontent.com/assets/12498256/7744652/72d58d6c-ffa5-11e4-99b9-2849e6950f83.png)

**Comment by mickaelandrieu** [comment]
Hi, I'm on it.

**Comment by mickaelandrieu** [comment]
already done by @jtrolle afaik :/
