### ISSUE TITLE
Page tree highlighted

### ISSUE THREAD

**Issue by geoffroyjourdan** [backbee/BbCoreJs#643]
When I click on tree to open the structure, the word Tree is not highlighted.
When I close the pop up, the word tree is highlighted.
it should be the other way around ? it's the same with Contents/media library
see files attached
![page tree](https://cloud.githubusercontent.com/assets/12498256/7744738/1bb892da-ffa6-11e4-959b-aad1aaa8de8b.png)
![page 3 highlighted](https://cloud.githubusercontent.com/assets/12498256/7744739/1e741d1e-ffa6-11e4-92d6-0500e9b77a0c.png)

**Comment by clementbonfils** [comment]
issue already reported thanks !
