### ISSUE TITLE
Loggin / IE 10 / chrome/ firefox

### ISSUE THREAD

**Issue by celine-user03** [backbee/BbCoreJs#644]
I try to log myself to the BO unsuccessfully. Loggin and password are ok...(i try twice...)
Of more the page does not refresh and remains blocked on this message (see picture below)
![sans titre-2](https://cloud.githubusercontent.com/assets/12509154/7744853/dc3d2444-ffa6-11e4-929c-e3e6d2aff44d.jpg)

**Comment by clementbonfils** [comment]
did you disactive your user in user management ?

**Comment by celine-user03** [comment]
yes it was...you can close this ticket
