### ISSUE TITLE
Contribution section opening

### ISSUE THREAD

**Issue by geoffroyjourdan** [backbee/BbCoreJs#645]
When I click on the contribution section, the Blocks part is automatically opened.

Should we remove this automatically section opening and let the user click on the section he watns to have access to ? 
![home backbee cms](https://cloud.githubusercontent.com/assets/12498256/7744909/6eb2888c-ffa7-11e4-8bba-4834b4b31631.png)

**Comment by clementbonfils** [comment]
Log in to backbee, by default no tab is selected
when you select a tab then leave the contribution area then come back, the tab will be the one you selected before leaving
