### ISSUE TITLE
wrong Title section highlighted 

### ISSUE THREAD

**Issue by geoffroyjourdan** [backbee/BbCoreJs#646]
When I open Tree for example, the tree word is not highlighted.
The Blocks section is still highlighted. It shouldn't.
We need to highlight the title of the section where we currently are on
![home 2backbee cms](https://cloud.githubusercontent.com/assets/12498256/7745016/41eab896-ffa8-11e4-8bfd-a80a75267597.png)

**Comment by clementbonfils** [comment]
issue already reported thank !
