### ISSUE TITLE
Create a user

### ISSUE THREAD

**Issue by celine-user03** [backbee/BbCoreJs#647]
In the pop fields are prefilled. They should be empty.
![sans titre-3](https://cloud.githubusercontent.com/assets/12509154/7745155/34f9cf72-ffa9-11e4-9296-9989eb56428b.jpg)

**Comment by clementbonfils** [comment]
these feilds are no values, they are displayed as exemples
you could not validate the form with these fake values for instance

**Comment by celine-user03** [comment]
so what is happened if John Doe is a name of someone in the company?
