### ISSUE TITLE
Pop up at top of the page

### ISSUE THREAD

**Issue by geoffroyjourdan** [backbee/BbCoreJs#648]
When a pop up is opened, if me move it at the top of the page it's on the users management/contribution/Extensions sections.

But on top of the right, the number is mixed with the title
see file attached
![home 3 backbee cms](https://cloud.githubusercontent.com/assets/12498256/7745177/5d074bb6-ffa9-11e4-8d10-d41d0fbf5895.png)

**Comment by clementbonfils** [comment]
this number is displayed to inform developers when there is a bug in their console.
we won't keep the number for the release
