### ISSUE TITLE
Create a user / IE 10

### ISSUE THREAD

**Issue by celine-user03** [backbee/BbCoreJs#650]
I can not create a user. An error window appears.
![sans titre-5](https://cloud.githubusercontent.com/assets/12509154/7745309/7fda2dba-ffaa-11e4-9e1f-f921a0ddd1c4.jpg)

**Comment by clementbonfils** [comment]
what is your version of IE ...? I can create one on IE11

**Comment by celine-user03** [comment]
I just try again in IE10. Still not works
