### ISSUE TITLE
IE 11/ Pop up in the Tool bar

### ISSUE THREAD

**Issue by Celiatas** [backbee/BbCoreJs#656]
In IE 11, at the top left of the page the number 1 is included in the tool bar
It should not appear

![capture5](https://cloud.githubusercontent.com/assets/12508720/7745712/8bf92f1c-ffad-11e4-883b-6b90661045cf.PNG)

**Comment by clementbonfils** [comment]
it is an indicator for developer to know when a bug is created
It won't be in the release version
