### ISSUE TITLE
[USERS] Général_ bug 02

### ISSUE THREAD

**Issue by celine-user03** [backbee/BbCoreJs#658]
When I reduce my window the users management area does not resize and popin is not placed in the center of the page. we do not see all the users or the popin
![sans titre-9](https://cloud.githubusercontent.com/assets/12509154/7745747/c5658a2a-ffad-11e4-969b-ff68333b03e5.jpg)

**Comment by clementbonfils** [comment]
RWD issue good for 1.1 version
