### ISSUE TITLE
Pop up : Page Statut / Firefox

### ISSUE THREAD

**Issue by Celiatas** [backbee/BbCoreJs#661]
When we log in Firefox, a pop in " Page statut" appears in the bottom right of the page
It does not appear either on Chrome or IE 11
Is it normal ?

![capture4](https://cloud.githubusercontent.com/assets/12508720/7745869/89f19b2c-ffae-11e4-97f4-0c996349fe80.PNG)

**Comment by clementbonfils** [comment]
it depends on wich tab you were before log out
if you were on the page tab (where the status pop in is displayed) you will have it after log in again
