### ISSUE TITLE
Page creation

### ISSUE THREAD

**Issue by geoffroyjourdan** [backbee/BbCoreJs#664]
I can right click and select create as many times as I want.
Then all the pop up are opened. 
Sholdn't we let only one page creation at a time possible ?  

It's the same behavior with edit/delete

![sous page 2 - backbee cms 2015-05-21 11-54-41](https://cloud.githubusercontent.com/assets/12498256/7746110/31f4c186-ffb0-11e4-956a-047d3a5bdce7.png)

**Comment by clementbonfils** [comment]
it should not be possible to reopen a creation page form once one is already open
via contextual menu
via new pas button

**Comment by clementbonfils** [comment]
change create page to new page also
