### ISSUE TITLE
Browse to erreur 404

### ISSUE THREAD

**Issue by geoffroyjourdan** [backbee/BbCoreJs#669]
From the tree menu, when I right click and select browse to I sometime have an 404 error.
But when I go back and try again it works.

Where this problem come from ? 
![erreur 404](https://cloud.githubusercontent.com/assets/12498256/7746398/3b01d348-ffb2-11e4-854b-426f990e9404.png)

**Comment by clementbonfils** [comment]
can teproduce the bug ..do you have more details of action, scenario

**Comment by geoffroyjourdan** [comment]
I was on IE, opened the tree and right click to one page and select browse to.

I just tried to reproduce the bug once again but couldn't. 
Maybe it was a one time bug..
