### ISSUE TITLE
content deleted but not in the menu tree

### ISSUE THREAD

**Issue by geoffroyjourdan** [backbee/BbCoreJs#679]
I deleted a page in the pop in content.

This page still appears in the menu tree
![home - backbee cms 2015-05-21 12-37-12](https://cloud.githubusercontent.com/assets/12498256/7746875/366b6372-ffb6-11e4-9e59-358cbdd57636.png)

**Comment by clementbonfils** [comment]
pop in content. ?

**Comment by geoffroyjourdan** [comment]
Yes from this pop in content
![page ie backbee cms](https://cloud.githubusercontent.com/assets/12498256/7749701/b2b4c568-ffcf-11e4-8bc0-c454f39c220d.png)
