### ISSUE TITLE
[CONTENT SELECTOR] add edit function in content list

### ISSUE THREAD

**Issue by geoffroyjourdan** [backbee/BbCoreJs#686]
In the media library list we have 3 buttons : see, delete, edit.

In the content list, edit is missing. Is it possible to add this function to have the possibility to edit the page you want directly from the list ?

**Comment by clementbonfils** [comment]
no because today contenst can be in the selector but not attached to any page
we will have edit when content vailable in content selector will always be attached to pages (no orphan contents)
