### ISSUE TITLE
Edit pop in media library

### ISSUE THREAD

**Issue by geoffroyjourdan** [backbee/BbCoreJs#688]
In media library, when I click on edit, the pop in is loading and nevers ends.. I can't edit the picture
![edit media library](https://cloud.githubusercontent.com/assets/12498256/7747205/cd88f614-ffb8-11e4-8d58-a3c6d612e480.png)

**Comment by clementbonfils** [comment]
is it on IE ?

**Comment by geoffroyjourdan** [comment]
IE and chrome
