### ISSUE TITLE
[USERS] Problem when I create a group with an existing name

### ISSUE THREAD

**Issue by Sylvain01** [backbee/BbCoreJs#692]
1) I create a group with an existing name
2) pop in "group save fail" 
- we should get a warning info "this group name is already taken, please select another name "
- I cannot create an other group and I need to refresh the page to create a new group

**Comment by clementbonfils** [comment]
warning message still missing

**Comment by ndufreche** [comment]
@clementbonfils please close this issue and create new one on error message missing ans tag it to 1.1
