### ISSUE TITLE
[USERS] Problem when you rename a group 

### ISSUE THREAD

**Issue by Sylvain01** [backbee/BbCoreJs#694]
1) I create a group
2) I rename the group and I use an existing name
3) no warning info
4) I have 2 groups with the same name > it is a problem 
![group-name](https://cloud.githubusercontent.com/assets/12500378/7748365/0ef88cbc-ffc4-11e4-97d6-e06f0a429d00.PNG)

**Comment by clementbonfils** [comment]
if i try to create a group with the same name i have a fail message but then i can't create a group anymore

**Comment by clementbonfils** [comment]
ok no error but i should not be able to change a groupe name to give it the same name as another one

**Comment by Sylvain01** [comment]
You're right
I should not be able to change a group name to give it the same name as another one
We need a warning info for example : "Existing name.  Please select another name"

**Comment by ndufreche** [comment]
The exact rules adopted is one group name by site, then you can have two groups with the same name but on different website.

**Comment by Sylvain01** [comment]
We need a warning info for example : "Existing name. Please select another name"

**Comment by clementbonfils** [comment]
still miss the info of failure
