### ISSUE TITLE
Search function in media library

### ISSUE THREAD

**Issue by geoffroyjourdan** [backbee/BbCoreJs#696]
When I look for a picture name in the media library it works.

Then if I close the pop in and open it again, the previous search function still works.

If we close the media library pop in and open it agian it should be new, with all the picture and no search function deployed

**Comment by clementbonfils** [comment]
@sylvain01
What do you think ?

**Comment by Sylvain01** [comment]
Geoffroy is right

**Comment by clementbonfils** [comment]
ok
