### ISSUE TITLE
Folder and sub folder media library

### ISSUE THREAD

**Issue by geoffroyjourdan** [backbee/BbCoreJs#697]
When I tried to create folder and subfolder, the cross is at one point hidden 

![home - backbee cms 2015-05-21 14-35-24](https://cloud.githubusercontent.com/assets/12498256/7748712/22eddbf2-ffc7-11e4-9c6d-e725b6a9a430.png)

**Comment by clementbonfils** [comment]
there is a little scroll bar at the buttom to go from left to right
