### ISSUE TITLE
[USERS] BackBee Users management / user in group

### ISSUE THREAD

**Issue by celine-user03** [backbee/BbCoreJs#700]
when I move the mouse over one of the users of the popin , the button is highlited but no action is possible. 
![13](https://cloud.githubusercontent.com/assets/12509154/7748822/844bd092-ffc8-11e4-8869-e22db1e4abb9.jpg)

**Comment by clementbonfils** [comment]
disable highlight on users if no action can be made

**Comment by ndufreche** [comment]
This is integration
