### ISSUE TITLE
New page section color

### ISSUE THREAD

**Issue by geoffroyjourdan** [backbee/BbCoreJs#707]
When I click on new page, tht pop in shows up but the section "New page" is not orange
When I close the pop in, the section "New page" is orange.

It should be : when I click on new page and the pop in shows up, the section should be orange.
When I close, the section is not orange anymore
![new page](https://cloud.githubusercontent.com/assets/12498256/7749227/e81f2846-ffcb-11e4-9dcd-7806e3b5effd.png)

**Comment by clementbonfils** [comment]
yes already reported !
