### ISSUE TITLE
Validation confirmation

### ISSUE THREAD

**Issue by geoffroyjourdan** [backbee/BbCoreJs#708]
When I select validate, 
A white pop in shows up with "validation confirmation". We don't know what to expect : something loading ? just closing the pop in ? 

![validation](https://cloud.githubusercontent.com/assets/12498256/7749397/7832b226-ffcd-11e4-891a-22ca92f0b18d.png)

**Comment by clementbonfils** [comment]
revision system fail after deleting some content
please
