### ISSUE TITLE
Users management / deleted a user

### ISSUE THREAD

**Issue by celine-user03** [backbee/BbCoreJs#710]
two points : 
-The color-coded buttons is not consistent with the rest of the site (see picture below)
![16](https://cloud.githubusercontent.com/assets/12509154/7749402/86777204-ffcd-11e4-911d-457d949cd732.jpg)

-Once the user was deleted he is always present in the list of the groups. I have to refresh the page to see him disappearing from groups

**Comment by clementbonfils** [comment]
yes that's right
Already reported
