### ISSUE TITLE
Duplicate pop in

### ISSUE THREAD

**Issue by Celiatas** [backbee/BbCoreJs#717]
1) I click to create a new user
2) Pop in cration opens
3) I display admin 's information 
4) A secondsecond pop in opens above the second

When a popin is open blocks the opening of other pop in

![capture26](https://cloud.githubusercontent.com/assets/12508720/7750535/1a513d78-ffd5-11e4-94c1-2e32a4492463.PNG)

**Comment by clementbonfils** [comment]
yes ! issue already reported
