### ISSUE TITLE
[User Management ] give names to popin

### ISSUE THREAD

**Issue by Celiatas** [backbee/BbCoreJs#718]
all pop in deployed have no name
You can not link them to any elements

**Comment by clementbonfils** [comment]
can you be more specific ?

I see only create user pop in without name and it's already reported

thanks !

**Comment by Celiatas** [comment]
1) create user pop in without name
![capture1](https://cloud.githubusercontent.com/assets/12508720/7752908/6f2f6b78-ffe2-11e4-94bf-ca41617a77a3.PNG)

2)User inforamtion pop in without name
![capture2](https://cloud.githubusercontent.com/assets/12508720/7752925/8c3a48aa-ffe2-11e4-92c3-733f68e86a1c.PNG)

3) User group pop in without name
![capture3](https://cloud.githubusercontent.com/assets/12508720/7752935/a0b40690-ffe2-11e4-9035-0d289020bfa7.PNG)

4) admin information pop in without name
![capture4](https://cloud.githubusercontent.com/assets/12508720/7752951/b67ec708-ffe2-11e4-8bda-681c97021d64.PNG)

5) Change password pop in without name
![capture5](https://cloud.githubusercontent.com/assets/12508720/7752973/cfae324a-ffe2-11e4-85cd-a93ec69d1576.PNG)

6) Delete group pop in without name 
![capture6](https://cloud.githubusercontent.com/assets/12508720/7752989/e6c97570-ffe2-11e4-8d02-677c1f8a6ca6.PNG)

7) delete user pop in without name 
![capture7](https://cloud.githubusercontent.com/assets/12508720/7753003/fd8743dc-ffe2-11e4-9a1a-4298935d33ee.PNG)

**Comment by clementbonfils** [comment]
give names to all these pop in
- [ ] Create user
- [ ] Users of the group
- [ ] Edit user
- [ ] Delete user
- [ ] Delete group
