### ISSUE TITLE
information under a picture 

### ISSUE THREAD

**Issue by geoffroyjourdan** [backbee/BbCoreJs#720]
In content, I added a picture via drag/drop.
It works but under the picture there is text like "picture credits : author name/source) we can't modify
Is this the normal process ? 
![picture](https://cloud.githubusercontent.com/assets/12498256/7751038/01fedcc8-ffd8-11e4-8589-994e76e8779b.png)

**Comment by clementbonfils** [comment]
these informations can be change in the picture form clicking on the pencil picto at the right top of the block
