### ISSUE TITLE
Tool Bar

### ISSUE THREAD

**Issue by Celiatas** [backbee/BbCoreJs#722]
![capture99](https://cloud.githubusercontent.com/assets/12508720/7751231/1e0af00e-ffd9-11e4-83c6-c54c3c29d91e.PNG)

In the toolbar we have a drop-down menu icon but there is no drop-down menu

**Comment by jtrolle** [comment]
We do not use dropdown for the main menu. Can you remove `<b class="caret"></b>` in `.bb5-navbar-primary` for :
- Users management
- Contribution
- Extensions
