### ISSUE TITLE
Options missing when editing a page 

### ISSUE THREAD

**Issue by geoffroyjourdan** [backbee/BbCoreJs#728]
On IE and Chrome, I do not have the 3 options (remove/edit/drag) when I edit one page
![summer 20152 - backbee cms 2015-05-21 17-21-37](https://cloud.githubusercontent.com/assets/12498256/7752157/2d01a7ec-ffde-11e4-95ea-19a24d582c43.png)

**Comment by clementbonfils** [comment]
on which bloc are you ? options difers from a block to another

**Comment by geoffroyjourdan** [comment]
I was on the exact same page on chrome, IE and mozilla.
It was an article block

**Comment by clementbonfils** [comment]
what options do you have instead ?

**Comment by geoffroyjourdan** [comment]
No one
