### ISSUE TITLE
User Creation

### ISSUE THREAD

**Issue by Celiatas** [backbee/BbCoreJs#729]
1) I create a user
2) a creation pop in opens
3) I do not close the pop in creation and I edit information for an existing user*
4) The two pop in are open 
5) I open a 3rd pop in ( admin's informations )

you can open multiple pop in on the same window

![capture5](https://cloud.githubusercontent.com/assets/12508720/7752441/c34bc344-ffdf-11e4-844d-b160cb682666.PNG)

**Comment by clementbonfils** [comment]
yes you are right 
the issue already reported
