### ISSUE TITLE
disable user search when pop in is open

### ISSUE THREAD

**Issue by Celiatas** [backbee/BbCoreJs#730]
1) I create a user
2) user creation's pop in is open
3 ) without closing the pop in creation, I can enter information in user search fields

this should not be impossible as long as the pop in is open

![capture2](https://cloud.githubusercontent.com/assets/12508720/7752527/488e88b6-ffe0-11e4-93bc-effcd1f8ba02.PNG)

**Comment by ndufreche** [comment]
@backbee/core-team This issue make sense for you ?

**Comment by mickaelandrieu** [comment]
not a bug for me.

**Comment by eric-chau** [comment]
First this is not a bug and it's very questionable cause user could want to search for users while he is creating a new one.
