### ISSUE TITLE
login out on a off line page must redirect to home page to prevent 404

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#735]
login out on a offline page must redirect to home page to prevent 404

**Comment by clementbonfils** [comment]
@crouillon what do you think ?

**Comment by clementbonfils** [comment]
cf 404 install ticket

**Comment by mickaelandrieu** [comment]
@clementbonfils do you consider this issue closed ? The 404 ticket is merged and validated.
