### ISSUE TITLE
Publishing and archiving pages are KO

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#746]
Publishing and archiving pages are KO

**Comment by clementbonfils** [comment]
can't test because i can't save this schedule of page

PATCH http://early.backbee.com/rest/1/page/13e2f9526f698a29ad62a84dd9950004 400 (Invalid patch operation: You are not allowed to replace `/publishing` for BackBee\NestedNode\Page.)

**Comment by mickaelandrieu** [comment]
Hmm... you may need to clear the cache of BackBee application (operation needs to be done on server)

**Comment by clementbonfils** [comment]
@eric-chau

**Comment by mickaelandrieu** [comment]
@clementbonfils I'm on it.
