### ISSUE TITLE
Contribution / Cancelled an action

### ISSUE THREAD

**Issue by celine-user03** [backbee/BbCoreJs#755]
When i want to cancelled an action:
The popin opens blank (see picture bellow)
The user can make nothing more
![20](https://cloud.githubusercontent.com/assets/12509154/7768990/b511ce62-0080-11e5-84c1-8f91e9d617a9.jpg)

**Comment by clementbonfils** [comment]
modifications about to be merged 
it is temporary and reported
thanks
