### ISSUE TITLE
[User management] prepare ACL for 1.0 release

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#765]
- [x] show "rights of the group" button
- [x] disable "new group" button
- [x] hide "delete group" button
- [ ] add a cancel button in the "rename" of a group form to prevent from reloading to quit
- [x] avoid rename of group with an identical group name of another group
- [x] remove a user of group
- [x] display list of rights of each group in the "rights of the group" pop in
Administrator : Rights on all the website and features
Contributor : Rights on creation, edition of pages. Can only view the rest of the website
Validator : Rights on creation, edition and publication of pages. Can only view the rest of the website

**Comment by mickaelandrieu** [comment]
to be honest, there is no chance for this feature to be released and finished before 28th of may.

**Comment by Sylvain01** [comment]
@crouillon : what can be done to meet our expectations ?

**Comment by ndufreche** [comment]
@Sylvain01 a quick point on this issue

Already done:
 - avoid rename of group with an identical group name of another group (need early upgrade)
 - reorder groups (need early upgrade and reinstallation)

Can be done really quickly:
 - disable "new group" button
 - hide "delete group" button

Take more times (order by less to higher time):
 - show "rights of the group" button (need some template upgrade and creation)
 - add a cancel button in the "rename" of a group form to prevent from reloading to quit (need form builder upgrade, can be more quick by @fkroockmann )
 - remove user from group (need some php change and upgrade, need to define a behavior and modify templates, work can be split for two person)

**Comment by clementbonfils** [comment]
![rights](https://cloud.githubusercontent.com/assets/10673014/7795628/0a6af980-02d7-11e5-9494-74fafd751a69.png)
