### ISSUE TITLE
unable user password to be sent by email

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#772]
unable user password to be sent by email

**Comment by mickaelandrieu** [comment]
@clementbonfils it's @ndufreche issue, not mine: I've just fixed some specific use case.

**Comment by clementbonfils** [comment]
add mailer config in BackBee standard

**Comment by ndufreche** [comment]
create mailer.yml in config folder

```yml
smtp: localhost
port: 1025
```

**Comment by mickaelandrieu** [comment]
this configuration don't work. I think we have to configure your preproduction environement to let @clementbonfils test your feature.

And then found a way to provide a mailer native configuration in installer. => https://github.com/backbee/BackBee/issues/433
