### ISSUE TITLE
Pop in to translate

### ISSUE THREAD

**Issue by Sylvain01** [backbee/BbCoreJs#778]
Pop in to translate
![remove](https://cloud.githubusercontent.com/assets/12500378/7797002/70667840-02e6-11e5-894a-c5c03b7125e1.PNG)

**Comment by ndufreche** [comment]
I will say, much remove this confirm "popin" and add a real popin with the popin manager.

**Comment by clementbonfils** [comment]
" Do you want to remove this content? "
