### ISSUE TITLE
It is sometimes difficult to close the "Block description" Pop in 

### ISSUE THREAD

**Issue by Sylvain01** [backbee/BbCoreJs#781]
1) I pick a block

![block description](https://cloud.githubusercontent.com/assets/12500378/7797606/b65ff3dc-02ee-11e5-9e26-ba66b17dfb34.PNG)

2) It is the wrong block so I want to select another block >  I pick another block
3) It is the wrong block so I want to select another block >  I pick another block
3) It is difficult to close the "Block description" Pop in > I have to click many times on the cross for closing the pop in

**Comment by clementbonfils** [comment]
close the previous block description pop in everytime I click on a new one

**Comment by mickaelandrieu** [comment]
Soooo boring, as I said popin is **never** a good option to display content. Now we have to fix behaviors all the time on all the popins -_-

**Comment by mickaelandrieu** [comment]
Hi, I'm on it.

**Comment by mickaelandrieu** [comment]
@clementbonfils fixed.

**Comment by clementbonfils** [comment]
prob of refresh
prob of double click

**Comment by mickaelandrieu** [comment]
yes, I'm on it.
