### ISSUE TITLE
Detail missing when you delete a content

### ISSUE THREAD

**Issue by Sylvain01** [backbee/BbCoreJs#782]
Detail missing when you delete a content > which following pages ?

![delete-content](https://cloud.githubusercontent.com/assets/12500378/7797920/17457b6e-02f3-11e5-9634-d608b194c20e.PNG)

**Comment by clementbonfils** [comment]
![orphaned](https://cloud.githubusercontent.com/assets/10673014/7798096/ad90cac2-02f5-11e5-936e-32f20ec7fd77.png)
