### ISSUE TITLE
Add style to the "remove" button for deleting users

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#799]
Add style to the "remove" button for deleting users

**Comment by ndufreche** [comment]
![screenshot from 2015-05-26 14 42 45](https://cloud.githubusercontent.com/assets/426139/7812753/9a7d29b0-03b5-11e5-8f8b-6070a15b5145.png)

**Comment by mickaelandrieu** [comment]
only add a css class "pull-right", I don't think we need to distrub @jtrolle for this kind of tasks ;)

**Comment by ndufreche** [comment]
template:
```
src/tb/apps/user/templates/user/list.item.twig
```

**Comment by ndufreche** [comment]
@mickaelandrieu is not enough

**Comment by jtrolle** [comment]
Replace button with `<button type="button" class="btn btn-default-grey btn-sm fa fa-times"></button>`
