### ISSUE TITLE
[TRAD] change menu tabs names

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#813]
Change the name in the tab and in the orange H1 underneath

Users management ---> User Management
Contribution ----> Dashboard
Extensions ------> Plugins

**Comment by ndufreche** [comment]
Contribution is not a Dashboard

**Comment by clementbonfils** [comment]
put "Edition" instead

Users management ---> User Management
Contribution ----> Edition
Extensions ------> Plugins
