### ISSUE TITLE
Add a wildcard system into Mediator

### ISSUE THREAD

**Issue by ndufreche** [backbee/BbCoreJs#83]
Mediator subscribe have to be understand wildcard in the namespace.

example :
```javascript
Mediator.subscribe('on:something:*', callback);
```
The callback have to be executed when someone publish 'on:something:happen' and 'on:something:iscoming'.

But wildcard can be acceptable only  on the last element of the name space.
```javascript
Mediator.subscribe('*:something:happen', callback);
```
and
```javascript
Mediator.subscribe('on:*:happen', callback);
```
These cases should not be processed

**Comment by fkroockmann** [comment]
Good idea :), it's very useful.

**Comment by ndufreche** [comment]
I transfer this issue in the good repo => backbee/core-js
