### ISSUE TITLE
[DELETE PAGE] If page has subpages

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#848]
In case a page has subpages, inform user in the deletation pop in with a BIG warning 

![delete](https://cloud.githubusercontent.com/assets/10673014/7857454/c071e8b4-0530-11e5-835d-01489794e545.png)

**Comment by ndufreche** [comment]
The correct text is:
The page you are about to delete contains subpages. All subpages will automatically be deleted if you confirm this action.
If you wish to keep these subpages please move them to another location
