### ISSUE TITLE
Access denied when validation with a contributor profile

### ISSUE THREAD

**Issue by geoffroyjourdan** [backbee/BbCoreJs#851]
I cant' validate a page as a validator 

I created an acocunt geoffroyjourdan
mdp : jourdan
I'am a validator.

When I want to validate a page, a pop in shows up with access denied and requires my log in and password
![page test backbee cms](https://cloud.githubusercontent.com/assets/12498256/7857850/24da4a64-0534-11e5-8a9c-b6bbe877219b.png)

**Comment by clementbonfils** [comment]
@crouillon

**Comment by crouillon** [comment]
Merged: backbee:#440
