### ISSUE TITLE
Create media selector element in formbuilder

### ISSUE THREAD

**Issue by fkroockmann** [backbee/BbCoreJs#88]
This element allow to revover a media into media selector.

For example:
![media-selector](https://cloud.githubusercontent.com/assets/9247945/5626723/9234b078-958f-11e4-8ce8-69a338c20fcd.png)

**Comment by mickaelandrieu** [comment]
to revover ? what do you mean ?

**Comment by fkroockmann** [comment]
He retrieve a media into media selector
