### ISSUE TITLE
I need 3 validation texts 

### ISSUE THREAD

**Issue by ndufreche** [backbee/BbCoreJs#935]
- [ ] when you do grouped page switch to online
- [ ] when you do grouped page switch to offline
- [ ] when you do grouped remove page and explain that the page in trash will be permanently removed

**Comment by clementbonfils** [comment]
Put the selected page(s) online?
Put the selected page(s) offline?
Remove the selected page(s)?
Warning : if the pages you remove are trash, they will be removed permanently
